//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public int ClassID { get; set; }
        public Nullable<int> ClassName { get; set; }
        public string Describe { get; set; }
        public string Image { get; set; }
    }
}
