//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entity
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Cours
    {
        public long CoursesID { get; set; }
        public string Title { get; set; }
        public Nullable<long> Price { get; set; }
        public Nullable<System.DateTime> DateOpen { get; set; }
        public string Des { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string Content { get; set; }
        public HttpPostedFileWrapper ImageFile { get; set; }
        public string open { get; set; }
        public string regis { get; set; }
    }
}
