//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entity
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Guide
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public string Des { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> GuideCateID { get; set; }
        public HttpPostedFileWrapper ImageFile { get; set; }
    }
}
